<a href="https://colab.research.google.com/github/YoonjJun/BoilerWiki/blob/main/Partner_Matching_Engine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x # only for the colab env

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn

SaaS partner matching program using Deep Learning

Data Preprocessing

In [ ]:
dataset =
(x_train, y_train), (x_test, y_test) = dataset()

Define Model

In [ ]:
# prompt: make neural network using tensorflow

import tensorflow as tf

model = tf.keras.Sequential([
  tf.keras.layers.Dense(64, activation='relu', input_shape=(10,)),
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dense(16, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10)

# Evaluate the model
model.evaluate(x_test, y_test)


NameError: name 'X_train' is not defined

In [ ]:
rank3_tensor1 = tf.Variable([ [ [1,2,3,4,]
                              ,[1,0,0,1]
                              ,[0,10,1,1] ]
                            ,[[0,0,0,1]
                             ,[1,0,0,0]
                             ,[0,1,1,0]] ])
rank3_tensor2 = tf.Variable([ [ [1,0,1,1,]
                              ,[1,0,0,1]
                              ,[0,0,1,1] ]
                            ,[[1,1,1,1]
                             ,[1,0,1,0]
                             ,[0,1,1,0]] ])

In [ ]:
tf.shape(rank3_tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [ ]:
tensor1 = tf.Variable([[1,2], [5,2]])
tensor2 = tf.Variable([[9,4], [1,1]])
print(tf.matmul(tensor1, tensor2))
print(tensor1 + tensor2)

tf.Tensor(
[[11  6]
 [47 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10  6]
 [ 6  3]], shape=(2, 2), dtype=int32)


In [ ]:
rank3_tensor1 = tf.reshape(rank3_tensor1, [ -1])
print(rank3_tensor1)

tf.Tensor([ 1  2  3  4  1  0  0  1  0 10  1  1  0  0  0  1  1  0  0  0  0  1  1  0], shape=(24,), dtype=int32)
